### ISSUE TITLE
Not working on macOS, just displays a loading sign

### ISSUE THREAD

**Issue by ayushhroyy** [manifestinteractive/weather-bar-app#18]
#### Overview:

_( a detailed overview of the problem this ticket will solve and the targeted audience )_

#### Acceptance Criteria:

_( issue will not be considered complete unless this list of criteria is met, e.g. intended usage, expected functionality, specific metrics met, etc. )_

#### Steps to Duplicate _( required for bug reports )_:

_( a step by step guide written for a person who might be looking at this for the first time )_

#### System Info _( required for bug reports )_:

_( e.g. "iPhone 6 iOS 8.3" or "OSX 10.10 and Google Chrome Version 44.0.2403.89 (64-bit)" )_

#### Relevant Documentation _( optional )_

_( e.g. Screenshots, Github Issues, etc )_

**Comment by Vfposselt** [comment]
Im getting the same issue here. Any workarounds?

**Comment by ayushhroyy** [comment]
I switched to linux actually lol i get a weather widget on gnome that's more superior 
![image](https://user-images.githubusercontent.com/77523847/150531179-37e3afbf-7004-4848-8b55-78b1240f3377.png)
