### ISSUE TITLE
Not working on Windows 11

### ISSUE THREAD

**Issue by p-bojkowski** [manifestinteractive/weather-bar-app#19]
Hi :)

app is not really working on Windows 11.
It's never ending loading...

![image](https://user-images.githubusercontent.com/74313141/129164553-7bd1a080-95ac-4c42-aa68-bf4982d06e5d.png)

When you click on about:

![image](https://user-images.githubusercontent.com/74313141/129164584-9355ce72-64f7-48b4-a10e-b5c5bd712d69.png)

![image](https://user-images.githubusercontent.com/74313141/129164608-0b58d25f-fc1b-4b0b-8d58-7239c390e9b2.png)

**Comment by tbarre** [comment]
Was this issue ever resolved?  I am having the very same issue.

**Comment by p-bojkowski** [comment]
@tbarre good question!
BUT check this: 
https://gearupwindows.com/how-to-display-weather-info-in-windows-11-taskbar/

+
https://www.intowindows.com/show-weather-info-on-windows-11-taskbar/

I have no idea how this is possible?

**Comment by manifestinteractive** [comment]
@p-bojkowski and @tbarre Windows 11 is not even available to the public ( and it won't be until some time in October apparently ), so there is no plan to support it right now ( sorry, this is free software guys )

Once it is available to the public, and I can update my operating system to the first stable public release, I will make a new release.  For now, I have update the website to inform users that this will NOT work on Windows 11 ( I actually did this a while ago for new users download this ).

But for now, if you want to use this, and you are currently on Windows 10, just know it's not going to work as it's not possible for me to create a build that will support this yet without forking out cash for developer access.

Again ... free app ;)

**Comment by RealAmes** [comment]
I've been using it all week since my Surface Studio Laptop arrived and I had to use Windows 11. Working great so far.

**Comment by manifestinteractive** [comment]
Anyone have a Windows 11 Machine they want to send me? ha ha.  I have a Microsoft Surface Pro 4, and went to update to Windows 11 the day it was released, and found out it is not compatible.  So, I STILL do not have a way to test this.

Thanks for the kind works @Djinn1 ... I may have gone a little overboard with the styling, as I really wanted every little thing to be pretty.  Heck, even made sure the orientation and phase of the moon actually matched where you were geographically.  It was a pretty nerdy adventure ;)

But ya, no one pays me for that stuff, so expensing a new laptop just for Windows 11 is overkill.  I could try to spin up a Virtual Instance, but those rarely have the same experiences as actual physical machines.

**Comment by RealAmes** [comment]
I sent a donation. I'm going to use it on all my Win 11 machines as they update. Great replacements for the one in Win 10.

**Comment by LaocheXe** [comment]
Works on mine, only issue is - it wont use my location. maybe because I live in a small town, idk.

**Comment by manifestinteractive** [comment]
I will be releasing a new version of this app within the next month now that I have a Windows 11 machine, and many people have reported issues on that platform. It is seeming like the main Electron wrapper that loads this app is failing now for some people, and can likely be fixed just by rebuilding with the latest version of Electron ( Windows 11 did not exist when this was first built ).

Sorry for the delay on this, I just did not have a machine I could install Windows 11 on until today, and will need some time to get this all wrapped up.  Once a new release is out, I will post back to this ticket so everyone knows.

**Comment by Djinn1** [comment]
> I will be releasing a new version of this app within the next month now that I have a Windows 11 machine, and many people have reported issues on that platform. It is seeming like the main Electron wrapper that loads this app is failing now for some people, and can likely be fixed just by rebuilding with the latest version of Electron ( Windows 11 did not exist when this was first built ).
> 
> Sorry for the delay on this, I just did not have a machine I could install Windows 11 on until today, and will need some time to get this all wrapped up. Once a new release is out, I will post back to this ticket so everyone knows.

Any news on when the update is coming? Can't wait :)

**Comment by SatjitSS** [comment]
> > I will be releasing a new version of this app within the next month now that I have a Windows 11 machine, and many people have reported issues on that platform. It is seeming like the main Electron wrapper that loads this app is failing now for some people, and can likely be fixed just by rebuilding with the latest version of Electron ( Windows 11 did not exist when this was first built ).
> > Sorry for the delay on this, I just did not have a machine I could install Windows 11 on until today, and will need some time to get this all wrapped up. Once a new release is out, I will post back to this ticket so everyone knows.
> 
> Any news on when the update is coming? Can't wait :)

I am seeing the earlier reported '_A JavaScript error occurred in the main process_' issue, with Windows 11 :'(

> NOTE: This does not work on Windows 11 ( that did not exist as an operating system when this was original compiled ). I will need to dedicate some time to reworking this to support Windows 11, but it might be a while before I can allocate free time to this.

Any ETA for a resolution would be super helpful 👍

**Comment by manifestinteractive** [comment]
@SatjitSS and everyone else asking, I am still working on the next version, there is quite a bit of stuff that needs to be knocked out if I am going to make a new release.  I can't just fix this one single issue and make a new release as that would make zero sense for me time wise due to the amount of work it takes just to get this app updated to work with the latest version of electron.

This is the current list of tickets getting worked on in v1.1.0:

https://github.com/manifestinteractive/weather-bar-app/milestone/1

And this is the project board where you can follow along with progress.  Once everything in the `In progress` column is in the `Done` column, I can make a new release :). Those tickets are in the priority I plan on tackling them.

https://github.com/manifestinteractive/weather-bar-app/projects/1

**Comment by SatjitSS** [comment]
@manifestinteractive: Thank you for the update and for all the time and attention, devoted to this project 🥇

**Comment by manifestinteractive** [comment]
Thanks, I am actively working on this, just super slow going as I can only do it when I am not working, and I have paid side projects on nights and weekends, so free time is kind of rare.

But if anyone wants to follow along, this is the branch that has the ongoing changes in it:

https://github.com/manifestinteractive/weather-bar-app/tree/release/v1.1.0

The good news is that once the app is deployed, everyone that has the app installed will get a notice that the newest version is available and they will get an in app prompt to download the latest app.  I built that into the very first version so the updates will be easier for folks.

**Comment by Paetrig** [comment]
Request an update on this as I have this issue too.

WORKAROUND: End the program, clear the local cache, and restart the computer. Not ideal but manageable, and not a permanent solution as the issue recurs in the next day or 2.

Otherwise, loving the app!
