### ISSUE TITLE
Icon in taskbar displays network error after every restart

### ISSUE THREAD

**Issue by danielp3011** [manifestinteractive/weather-bar-app#29]
#### Overview:

When I restart the computer each time the icon in the taskbar first shows an error message ("network"/"connection" error.
Reloading fixes this.

#### Acceptance Criteria:
Expected behaviour: Show temperature in the taskbar without an error after each restart.

#### Steps to Duplicate _( required for bug reports )_:
Restart device.

#### System Info _( required for bug reports )_:

Windows 11, 21H2, OS build 22000.318, 64 bit

#### Relevant Documentation _( optional )_

_( e.g. Screenshots, Github Issues, etc )_

**Comment by Whetdesert** [comment]
Same issue for me, though restarting is not fixing it today. I am receiving a status code 502 error.
![image](https://user-images.githubusercontent.com/94636115/142464946-93996e5f-bb14-4349-ac29-ceeea552426b.png)

This is the version of Windows 11 I am running:
Edition	Windows 11 Pro Insider Preview
Version	Dev
Installed on	‎11/‎18/‎2021
OS build	22504.1000
Experience	Windows Feature Experience Pack 1000.22504.1000.0

**Comment by manifestinteractive** [comment]
@Whetdesert this is a separate issue that started today.  Looks like the OpenWeatherData API I am using is failing.  I am looking into what is going on there right now, as this will mean it is failing for everyone, which is rather serious.  Could be related, possible @danielp3011 started experiencing the issue before anyone else.

**Comment by Whetdesert** [comment]
@manifestinteractive Ok, thank you for the update! Looking forward to the fix as this is a beautiful little app. Let me know if I can help with testing or anything.

**Comment by manifestinteractive** [comment]
@Whetdesert looks like it was actually MY API that failed ( oops ).  After several years of running without issues, looks like a server update was applied that paused some of the services running.  I just restarted them and things are back up and running.

@danielp3011 can you confirm things are working for you?  You reported your issues before it appeared API went down, but you might have just been the first person to start experiencing the results.  Would be good to know if this is also fixed for you, or if you are experiencing a separate issue.
