### ISSUE TITLE
[Feature Request] Display Condition and Temperature

### ISSUE THREAD

**Issue by TurtleP** [manifestinteractive/weather-bar-app#32]
#### Overview:

(For context: I am running Windows 11)

One thing that I originally liked from the Windows 10 weather widget on the taskbar was that it showed the current conditions and temperature at the same time. I think that it would be nice if WeatherBar also did this.

#### Acceptance Criteria:

WeatherBar should allow me to see both the current condition and temperature at a glance. (Although, another issue is that the icons and text are a bit small already, so it's hard to see, at least on my 1440p monitor.)

#### Relevant Documentation

N/A

**Comment by manifestinteractive** [comment]
This was not available as a feature with Electron on Windows before.  I will check to see if the latest version of Electron supports showing two parts for the next release, but it's probably unlikely.  This is not a "native" windows app, but an Electron app that tries its best to work on all platforms.
