### ISSUE TITLE
not working with windows 11

### ISSUE THREAD

**Issue by EmmanuellaD** [manifestinteractive/weather-bar-app#36]
It was working fine before but for the past month, the app doesn't want to start

**Comment by JacksonCampbell99** [comment]
I just installed it the other day and am having the same problem.

**Comment by StatsMaven** [comment]
Have to agree with the inability to execute Weather Bar in Windows/11 Version 22H2 Build 22621.160
Installation appears to complete and App is listed as installed but no means of activating / executing it

**Comment by manifestinteractive** [comment]
Closing this as it's a duplicate of #19 ( your ticket was technically first, but there is more activity in #19 )
