### ISSUE TITLE
Doesn't work on Mac, just doesn't load. Any help?

### ISSUE THREAD

**Issue by Dipolarfish** [manifestinteractive/weather-bar-app#38]
#### Relevant Documentation _( optional )_ Screenshot

![image](https://user-images.githubusercontent.com/98614653/151621653-10a3143a-1201-4e55-80b3-c3481edbf683.png)

**Comment by Dipolarfish** [comment]
The JavaScript error shows up when I right click on the menu bar icon and select About Weather Bar

**Comment by manifestinteractive** [comment]
There seems to be an issue with the Electron wrapper that runs this app.  The actual error in your JS file is a native Electron feature ( not my code ) and seems to be breaking even just trying to open their native dialog.

I will be releasing a new version of this app within the next month now that I have a Windows 11 machine, and many people have reported issues on that platform.  I realize this is macOS, but it is seeming like the main Electron wrapper that loads this app is failing now for some people.

**Comment by Dipolarfish** [comment]
I'll happily pay for a functional version of this app.. I'm sure others will too.

**Comment by manifestinteractive** [comment]
Sorry for the delay, this app seems to be working fine for everyone I have had test on MacOS, clean install and everything, so I honestly can't figure out why your machine is having issues, and can't justify spending time trying to track down hypothetical problems that I can't actually test.

My hope is that the new version I am working on will address whatever issues you are having.  If you are interested in testing an early version of v1.1.0 let me know.

I will continue leaving this ticket open, but there is quite a lot of stuff I need to complete in v1.1.0 that need to be tested on Windows 10, Windows 11, MacOS and Linux Distros, and I previously just did not have time to tackle all of that.  I am currently working on organizing everything and created a new milestone for v1.1.0 that contains all the issues that I plan on addressing with that.
