### ISSUE TITLE
[Bug] Weather Bar application doesn't open above the icon in the system tray

### ISSUE THREAD

**Issue by JacksonCampbell99** [manifestinteractive/weather-bar-app#40]
#### Overview:

Weather Bar opens above the system tray icons skewed over to the left. It is not even centered over the `Show hidden icons` arrow. I believe it was centered properly above its icon before this latest Windows update. Before I noticed this issue, I had always had the Weather Bar icon as the last icon on the left in the system tray, so it's slightly possible it was always like this on Windows 11 and I didn't notice because it was partially over the icon in the system tray. But I think it had been centered over the Weather Bar icon before this last Windows update which changed/removed system tray features and messed the tray up.

#### Steps to Duplicate _( required for bug reports )_:

Check Weather Bar on Windows 11. If it opens above its icon, then maybe it has something to do with my latest version of Windows 11 and its new system tray changes. Test it with multiple system tray icons showing on the taskbar, and set the Weather Bar icon as furthest right.

#### System Info _( required for bug reports )_:

Edition:	Windows 11 Pro
Version:	22H2
Installed on:	‎3/‎23/‎2022
OS build:	22581.200
Experience:	Windows Feature Experience Pack 1000.22581.200.0

#### Relevant Documentation _( optional )_

<img width="419" alt="image" src="https://user-images.githubusercontent.com/76508020/160756424-07efc418-2682-4125-9993-a8151ff32daf.png">

**Comment by manifestinteractive** [comment]
I've checked this on windows 10 and windows 11 and cannot duplicate it.  It consistently loads centered over the icon that launched it.  I will leave this open though until the next app release comes out so we can see if the newest version of Electron addresses this issue.
