### ISSUE TITLE
Change Color in Task bar Icon

### ISSUE THREAD

**Issue by wmaleesha** [manifestinteractive/weather-bar-app#45]
![image](https://user-images.githubusercontent.com/90347923/177254417-e6e49012-2fc0-496d-bb6b-1f739f38e92a.png)

solve this

**Comment by manifestinteractive** [comment]
try again, like I am a human being that is doing this free of charge ;)

**Comment by manifestinteractive** [comment]
Not enough information provided to work on this issue.
