### ISSUE TITLE
Cannot find my city

### ISSUE THREAD

**Issue by boobiesboob** [manifestinteractive/weather-bar-app#46]
Hi,
I leave in Darmstadt but I cannot find the city in the drop menu. please fix. looks like there are not all cities are included. thx you and have a nice Day.
E.

**Comment by manifestinteractive** [comment]
These cities are not something this program provides.  This is an external lookup using third party services.  If your city is not listed, then it is not supported by the weather API I am using.  Not much I can do about that.
